version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/Japanizer
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_PASSWORD: password
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-volume:
