version: '3'
services:
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/Japanizer/public
      - tmp-data:/Japanizer/tmp
    ports:
      - "80:80"
    depends_on:
      - app
    tty: true
    stdin_open: true
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Japanizer
      - public-data:/Japanizer/public
      - tmp-data:/Japanizer/tmp
      - log-data:/Japanizer/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  public-data:
  tmp-data:
  log-data:
  db-volume:
